baseURL = "https://www.szpunar-terapiacbt.pl"
languageCode = "pl-pl"
paginate = 6
theme = "portio"
title = "Małgorzata Szpunar - Terapie"
# Main Menu
[[menu.main]]
name = "Strona Główna"
url = "#home"
weight = 1
[[menu.main]]
name = "O mnie"
url = "#about"
weight = 2
[[menu.main]]
name = "Oferta"
url = "#service"
weight = 3
[[menu.main]]
name = "Opinie"
url = "#testimonials"
weight = 4
#[[menu.main]]
#name = "Resume"
#url = "#resume"
#weight = 5
#[[menu.main]]
#name = "Skills"
#url = "#skills"
#weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 5
[[menu.main]]
name = "Kontakt"
url = "#contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "O mnie"
url = "about"
weight = 1
#[[menu.sitemap]]
#name = "Frequently Ask Question"
#url = "#"
#weight = 2
#[[menu.sitemap]]
#name = "Polityka prywatności"
#url = "#"
#weight = 2
#[[menu.sitemap]]
#name = "Ostatni artykuł"
#url = "#"
#weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Wszystkie prawa zastrzeżone © Cudostrona.pl"
footerLogo = "images/contact/navbar1.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo1.png"

[params.address]
address = "Fiszera 6/1 80-231 Gdańsk"
email = "m.szpunar@op.pl"
#openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+48 697 777 020"

[params.map]
APIkey = "AIzaSyBFCgRqOFXFOGb6EO1QOBtYBgDhtsQKkAY"
latitude = "54.374133275438695"
longitude = "18.61425223438593"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
#[[params.social]]
#icon = "fa-linkedin-square"
#url = "https://www.linkedin.com/"
#weight = 2
#[[params.social]]
#icon = "fa-pinterest-square"
#url = "https://www.pinterest.com/"
#weight = 3
#[[params.social]]
#icon = "fa-twitter-square"
#url = "https://twitter.com/"
#weight = 4
